#!/usr/bin/env python

Import("env")
Import("env_modules")

env_steerperlin = env_modules.Clone()

#env_steerperlin(CXXFLAGS=["-fopenmp"])
#env_steerperlin(CXXFLAGS=["-mavx2"])
#env_steerperlin(LIBS=["omp"])

module_obj = []

env_steerperlin.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

#env.Append(LINKFLAGS = ['-fopenmp'])
#env.Append(CXXFLAGS = ['-mavx2'])
